USE BANCO

CREATE PROCEDURE LOGIN @CPF INT, @SENHA VARCHAR(200)
AS
BEGIN TRY
SELECT * FROM CONTA_CORRENTE WHERE CPF = @CPF AND SENHA = @SENHA
END TRY
BEGIN CATCH
RAISERROR('LOGIN INVÁLIDO', 16, 1)
END CATCH
GO;


--essas duas merda tão errada

CREATE PROCEDURE LOGIN_PROC @CPF INT, @SENHA VARCHAR(200)
AS
BEGIN

--SELECT * FROM CONTA_CORRENTE WHERE CPF = @CPF AND SENHA = @SENHA


DECLARE @TESTE VARCHAR(200) = 11

IF @TESTE>10
BEGIN
PRINT('O')
END

--RAISERROR('LOGIN INVÁLIDO', 16, 1) ;

END



EXEC LOGIN_PROC @CPF = 504, @SENHA = '246'




